apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: technicalassessment-namespace
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
